---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pebblr-local-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: pebblr-local-ca
  secretName: pebblr-local-ca-secret
  duration: 87600h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
