---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pebblr-local-tls
  namespace: pebblr
spec:
  secretName: pebblr-local-tls
  duration: 8760h
  renewBefore: 720h
  commonName: pebblr.local
  dnsNames:
    - pebblr.local
  issuerRef:
    name: pebblr-local-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
