apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pebblr.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pebblr.labels" . | nindent 4 }}
data:
  API_PORT: {{ .Values.config.apiPort | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  WEB_DIST_PATH: {{ .Values.config.webDistPath | quote }}
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  DB_SSL_MODE: {{ .Values.database.sslMode | quote }}
  AUTH_TENANT_ID: {{ .Values.auth.tenantId | quote }}
  AUTH_CLIENT_ID: {{ .Values.auth.clientId | quote }}
  AUTH_AUDIENCE: {{ .Values.auth.audience | quote }}
  AUTH_ISSUER_URL: {{ .Values.auth.issuerUrl | quote }}
  SECRET_MOUNT_PATH: {{ .Values.secrets.mountPath | quote }}
  TENANT_CONFIG_PATH: {{ .Values.config.tenantConfigPath | quote }}
