{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "pebblr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pebblr.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ include "pebblr.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.secrets.dbPasswordKey }}
      remoteRef:
        key: {{ .Values.secrets.dbPasswordKey }}
    - secretKey: {{ .Values.secrets.dbUrlKey }}
      remoteRef:
        key: {{ .Values.secrets.dbUrlKey }}
    - secretKey: {{ .Values.secrets.jwtSecretKey }}
      remoteRef:
        key: {{ .Values.secrets.jwtSecretKey }}
    {{- if .Values.secrets.demoSigningKeyKey }}
    - secretKey: {{ .Values.secrets.demoSigningKeyKey }}
      remoteRef:
        key: {{ .Values.secrets.demoSigningKeyKey }}
    {{- end }}
{{- end }}
