{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "pebblr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pebblr.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ include "pebblr.fullname" . }}-gw
      namespace: {{ .Release.Namespace }}
  {{- if .Values.tls.hostname }}
  hostnames:
    - {{ .Values.tls.hostname | quote }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "pebblr.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
