{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "pebblr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pebblr.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.istio.host | quote }}
  gateways:
    - {{ .Values.istio.gatewayNamespace | default .Release.Namespace }}/{{ .Values.istio.gatewayName }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "pebblr.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
