apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-migrate-%d-%s" (include "pebblr.fullname" .) .Release.Revision (now | date "20060102150405") | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pebblr.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "pebblr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      serviceAccountName: {{ include "pebblr.serviceAccountName" . }}
      automountServiceAccountToken: false
      restartPolicy: Never
      securityContext:
        {{- include "pebblr.podSecurityContext" . | nindent 8 }}
      volumes:
        {{- include "pebblr.secretsVolume" . | nindent 8 }}
      containers:
        - name: migrate
          {{- include "pebblr.image" . | nindent 10 }}
          command:
            - /app/migrate
            - -dsn-file
            - {{ .Values.secrets.mountPath }}/{{ .Values.secrets.dbUrlKey }}
            - -migrations-path
            - /app/migrations
          volumeMounts:
            {{- include "pebblr.secretsVolumeMount" . | nindent 12 }}
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            {{- include "pebblr.containerSecurityContext" . | nindent 12 }}
